# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title robustseEigen
#' @description `robustseEigen` fits cluster robust standard errors
#'   with C++Eigen across markers.
#'
#' @param es a matrix of residuals
#'
#' @param xs a matrix of covariates
#'
#' @param cs a vector of clusters
#'
#' @param xxs a matrix of XtX
#'
#' @param covs an empty variance-covariance matrix
#'
#' @return `robustseEigen` returns a matrix of robust standard errors
#'   where the rows are the CpGs and the columns are the covariates
#'   including the intercept.
#'
#' @author James R Staley <jrstaley95@gmail.com>
#'
#' @noRd
#' @md
robustseEigen <- function(es, xs, cs, xxs, covs) {
  .Call("_lmrse_robustseEigen", PACKAGE = "lmrse", es, xs, cs, xxs, covs)
}
